### ISSUE TITLE
首页文章列表出现重复

### ISSUE THREAD

**Issue by kanon-H** [jiewenhuang/halo-theme-joe3.0#128]
### 是什么版本出现了此问题？

2.10.0

### 发生了什么？

大佬你好，我又新建了个halo容器，测试了下这个首页文章重复的问题，从halo2.10.0,主题版本为
1.1.4，容器启动后，不做任何操作，直接安装joe3主题，然后再主题设置中将文章加载形式设置为加载，访问首页，默认的halo halo文章页面也会展示两个；麻烦大佬给看下呢
<img width="1209" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/108659129/5026c882-d52b-4bf2-af4e-4dd514238e91">
<img width="668" alt="image" src="https://github.com/jiewenhuang/halo-theme-joe3.0/assets/108659129/207a6a4d-9e4b-4cae-af1c-e1eaa8637a38">
```
version: "3.3"
services:
  # 个人博客 halo
  halo:
    image: halohub/halo:2.10
    container_name: halo
    restart: unless-stopped
    network_mode: mynet
    volumes:
      - ./halo/data:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --spring.r2dbc.url=r2dbc:pool:mysql://127.0.0.1:3306/halo-test
      - --spring.r2dbc.username=halo-test
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=halo-test
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      #- --halo.external-url=https://abcde
      # 初始化的超级管理员用户名
      - --halo.security.initializer.superadminusername=admin
      # 初始化的超级管理员密码
      - --halo.security.initializer.superadminpassword=87654321
```
