### ISSUE TITLE
Waline评论的gif导致footer异常·续

### ISSUE THREAD

**Issue by Einstein-schrodinger** [jiewenhuang/halo-theme-joe3.0#170]
### 是什么版本出现了此问题？

1.1.7

### 发生了什么？

gif的样式进行了修改，但是只有post文章页生效，其余页面未引入该样式。

虽然gif显示在上方可以有效避免footer异常问题，但是个人认为在下方显示更符合一般习惯
建议如下：
```css
/*原始*/
.wl-gif-popup.display {
    opacity: 1;
    visibility: visible;
    transform: none;
}

.wl-gif-popup.display {
    bottom: 100% !important;
    top: auto !important;
}


/*修改*/
.wl-gif-popup.display {
    opacity: 1;
    visibility: visible;
    transform: none;
    overflow-y: hidden;
    max-height: 245px!important;
}


/*原始*/
.wl-gallery {
    display: flex;
    overflow-y: auto;
    max-height: 80vh;
}

.wl-gallery {
    max-height: 30vh !important;
}

/*修改*/
.wl-gallery {
    display: flex;
    overflow-y: auto;
    max-height: 195px!important;
}

/*原始*/
.page-journals .joe_detail {
    position: relative;
    overflow-y: hidden; 
}

/*修改*/
.page-journals .joe_detail {
    position: relative;
   /*对瞬间页面最底部动态的回复评论的评论表情以及gif超出区域不进行覆盖*/
    /* overflow-y: hidden; */
}
```
`overflow-y: hidden; `
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/7713603d-2c94-4a95-812b-470fe8f89148)

`/* overflow-y: hidden; */ `
![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/62790820/a4bab06e-0bf4-4392-84ac-3bfb34184a92)
