### ISSUE TITLE
友链建议

### ISSUE THREAD

**Issue by wxyShine** [jiewenhuang/halo-theme-joe3.0#245]
### 描述一下此特性

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/42802152/8f6e78f1-812b-4e5b-a0ea-ed157ea9a196)

能增加个控制默认友链页面评论的开关不？

![image](https://github.com/jiewenhuang/halo-theme-joe3.0/assets/42802152/f1896315-d2da-4bf0-b957-433652c6af75)
后台显示未知  想着直接给评论关了。

**Comment by wxyShine** [comment]
可以给这个加上
```yml
- $formkit: radio
  name: link_enable_comment
  label:  友链页面-开启评论区
  value: true
  options:
    - value: true
      label:  开启
    - value: false
      label:  关闭
- $formkit: singlePageSelect
  name: link_comment_id
  label:  友链页面-评论区ID
  placeholder: '请选择一个页面作为友链页面的评论区ID'
  help: '友链页面没有 ID，需要指定一个自定义页面的 ID 用于评论，被指定的页面评论区将作为友链的评论区，未选择时则友链界面不显示评论区。'
```
